/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class nativeinterfaces_MarketDataNativeInterface */

#ifndef _Included_nativeinterfaces_MarketDataNativeInterface
#define _Included_nativeinterfaces_MarketDataNativeInterface
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     nativeinterfaces_MarketDataNativeInterface
 * Method:    subscribeListener
 * Signature: (Llisteners/DefaultCTPListener;)V
 */
JNIEXPORT void JNICALL Java_nativeinterfaces_MarketDataNativeInterface_subscribeListener
  (JNIEnv *, jobject, jobject);

/*
 * Class:     nativeinterfaces_MarketDataNativeInterface
 * Method:    unSubscribeListener
 * Signature: (Llisteners/DefaultCTPListener;)V
 */
JNIEXPORT void JNICALL Java_nativeinterfaces_MarketDataNativeInterface_unSubscribeListener
  (JNIEnv *, jobject, jobject);

/*
 * Class:     nativeinterfaces_MarketDataNativeInterface
 * Method:    sendLoginMessage
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_nativeinterfaces_MarketDataNativeInterface_sendLoginMessage
  (JNIEnv *, jobject, jstring, jstring, jstring, jstring);

/*
 * Class:     nativeinterfaces_MarketDataNativeInterface
 * Method:    sendQuoteRequest
 * Signature: ([Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_nativeinterfaces_MarketDataNativeInterface_sendQuoteRequest
  (JNIEnv *, jobject, jobjectArray);

/*
 * Class:     nativeinterfaces_MarketDataNativeInterface
 * Method:    sendUnsubscribeQuoteRequest
 * Signature: ([Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_nativeinterfaces_MarketDataNativeInterface_sendUnsubscribeQuoteRequest
  (JNIEnv *, jobject, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
